### ISSUE TITLE
Race condition in h-scaling-integration between Coordinator, Juju app leader and node going away

### ISSUE THREAD

**Issue by phvalguima** [canonical/opensearch-operator#156]
I am seeing what seems to me as a race condition between several nodes in the h-scaling-integration, at our CI.

This is one example of failed run: https://github.com/canonical/opensearch-operator/actions/runs/7199744236/job/19612482542

The failure happens in `tests/integration/ha/test_horizontal_scaling.py::test_safe_scale_down_roles_reassigning`.

The main issue in that run happens at `20:15:{12,19}`. During this time period:
- opensearch/0 is [selected as new CM node, and given it is juju app leader, it immediately restarts itself](https://pastebin.ubuntu.com/p/z9nDTGmhmc/)
    (it is also possible to see that, at 20:15:13 in opensearch/0, the cluster is considered *green* state)
- opensearch/0 restarts between 20:15:15 and 20:15:16: https://pastebin.ubuntu.com/p/Mx6B45z2gH/
- opensearch/5, as a coordinator, and at 20:15:12 it marks the node opensearch/0 as "faulty": https://pastebin.ubuntu.com/p/YgHS2hV3yy/
- opensearch/2 will detect opensearch/0 is gone at 20:15:12, then at 20:15:16, the charm stops the unit for the tear down: https://pastebin.ubuntu.com/p/ZhYHV2JPDH/

So, we have opensearch/5 having to deal 2x nodes going away at the same time, in a 4-node cluster.

The unit opensearch/2 will fail to finish `storage-detaching`: https://pastebin.ubuntu.com/p/8wTTBKzrK5/
Because opensearch/5 set the cluster in Red as it could not copy/move some of the shard replicas to deal with opensearch/2 going away.
Besides that, CI is running with:
```
automatically-retry-hooks:
  value: false
  source: model
```
https://pastebin.ubuntu.com/p/488WTZBRHZ/

Which means, for the next 20 minutes, `storage-detaching` will never be retried and the test will fail.

--------------------------------------------------------------------------------------------------------------

Proposal:

I do think we should keep that value as `automatically-retry-hooks=false`. That will highlight race conditions as this one.

I believe one fix would be to check the cluster health before stopping the opensearch service, within `storage-detaching` and to have a retrial within the hook, as such:
```
with retry_x_times:
    if cluster_is_healthy:
        stop_service
    if wait_until_cluster_is_healthy_or_timeout:
        finish_hook_and_exit
    raise Exception
```

That way, node opensearch/2 would've noticed opensearch/0 is leaving and waited for the cluster to settle before it decides to leave itself. Also, if  the cluster does not return to a healthy state, i.e. first cluster_is_healthy returns `false` every time; then we are protected against multiple nodes change state at once as happened in this case, because stop will never happen.

**Comment by phvalguima** [comment]
I think, for that bug, we need to also run this check here: 
```
                    if health_color == HealthColors.RED:
                        raise OpenSearchHAError(ClusterHealthRed)
```

In here: https://github.com/canonical/opensearch-operator/blob/a38e7743ba47ae5505e25bfcccaf34f739cebbf4/lib/charms/opensearch/v0/opensearch_base_charm.py#L406

That way, we avoid stopping one unit while another unit is restarting. Also, I'd add a retry there, so retry some XX amount of time before giving up on storage-detaching:
```
....
        self.peers_data.delete(Scope.APP, "security_index_initialised")

+        for attempt in Retrying(stop=stop_after_attempt(5), wait=wait_fixed(wait=10)):
+            with attempt:
                # we attempt to flush the translog to disk
+                if self.opensearch.is_node_up() and health_color != HealthColors.RED:
                    try:
                        self.opensearch.request("POST", "/_flush?wait_for_ongoing")
                    except OpenSearchHttpError:
                        # if it's a failed attempt we move on
                        pass
                   try:
                       self._stop_opensearch()
....
```

**Comment by phvalguima** [comment]
I think the root cause here is [this section of the code](https://github.com/canonical/opensearch-operator/blob/main/lib/charms/opensearch/v0/opensearch_base_charm.py#L370-L384).

As the description mentions:
> opensearch/0 is [selected as new CM node, and given it is juju app leader, it immediately restarts itself](https://pastebin.ubuntu.com/p/z9nDTGmhmc/) (it is also possible to see that, at 20:15:13 in opensearch/0, the cluster is considered green state)

In the logs:
```
2023-12-13T20:37:52.7494152Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Emitting Juju event opensearch_peers_relation_departed.
2023-12-13T20:37:52.7495501Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Getting secret app:admin-password
2023-12-13T20:37:52.7496694Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Starting new HTTPS connection (1): 10.102.124.173:9200
2023-12-13T20:37:52.7497297Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: https://10.102.124.173:9200 "GET /_nodes HTTP/1.1" 200 90460
2023-12-13T20:37:52.7497842Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Getting secret app:admin-password
2023-12-13T20:37:52.7498657Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Starting new HTTPS connection (1): 10.102.124.173:9200
2023-12-13T20:37:52.7500021Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: https://10.102.124.173:9200 "GET /_nodes HTTP/1.1" 200 90460
2023-12-13T20:37:52.7502638Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Suggesting - Addition of 'CM' to data: opensearch-0
2023-12-13T20:37:52.7506126Z unit-opensearch-0: 20:15:12 DEBUG unit.opensearch/0.juju-log opensearch-peers:1: Emitting custom event <AcquireLock via OpenSearchOperatorCharm/on/service_acquire_lock[932]>.
```

Then, opensearch/0 is running the peer relation departed routine and ends up selecting itself as the next CM role, which demands a restart.
That means the method: `self._compute_and_broadcast_updated_topology` is being called, and hence the check just before is returning true:
```
        if len(remaining_nodes) == self.app.planned_units():
            self._compute_and_broadcast_updated_topology(remaining_nodes)
```

The best way here is to, instead of checking the self.app.planned_units(), then try to get the status of the departing node directly and defer the departed event.

**Comment by phvalguima** [comment]
I have a PR that adds logging of indices status and shards on every update-status. I could get that PR to reproduce this same issue in: https://github.com/canonical/opensearch-operator/actions/runs/7793269450/job/21291970755

Checking the crashdump content, I can see the following steps.

1) Failure happens on node opensearch/3, at:
```
2024-02-06 22:12:40 DEBUG unit.opensearch/3.juju-log server.go:325 https://10.112.36.96:9200 "GET /_cluster/health?wait_for_status=green&timeout=1m HTTP/1.1" 408 447
2024-02-06 22:12:40 INFO unit.opensearch/3.juju-log server.go:325 Health: {'cluster_name': 'opensearch-7ypt', 'status': 'red', 'timed_out': True, 'number_of_nodes': 3, 'number_of_data_nodes': 3, 'discovered_master': True, 'discovered_cluster_manager': True, 'active_primary_shards': 5, 'active_shards': 14, 'relocating_shards': 0, 'initializing_shards': 0, 'unassigned_shards': 2, 'delayed_unassigned_shards': 0, 'number_of_pending_tasks': 0, 'number_of_in_flight_fetch': 0, 'task_max_waiting_in_queue_millis': 0, 'active_shards_percent_as_number': 87.5}
2024-02-06 22:12:40 ERROR unit.opensearch/3.juju-log server.go:325 [Errno 111] Connection refused
2024-02-06 22:12:40 ERROR unit.opensearch/3.juju-log server.go:325 Cannot connect to the OpenSearch server...
2024-02-06 22:12:40 ERROR unit.opensearch/3.juju-log server.go:325 [Errno 111] Connection refused
2024-02-06 22:12:40 DEBUG unit.opensearch/3.juju-log server.go:325 Getting secret app:admin-password
2024-02-06 22:12:40 DEBUG unit.opensearch/3.juju-log server.go:325 Starting new HTTPS connection (1): 10.112.36.96:9200
2024-02-06 22:12:40 DEBUG unit.opensearch/3.juju-log server.go:325 https://10.112.36.96:9200 "DELETE /.ops_lock HTTP/1.1" 200 21
2024-02-06 22:12:40 ERROR unit.opensearch/3.juju-log server.go:325 Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-3/charm/./src/charm.py", line 94, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-3/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-opensearch-3/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-opensearch-3/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-opensearch-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-opensearch-3/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-opensearch-3/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 425, in _on_opensearch_data_storage_detaching
    raise OpenSearchHAError(ClusterHealthRed)
```

Right before, unit `opensearch/3` registered everything as working, with the following indices:
```
2024-02-06 22:11:17 DEBUG unit.opensearch/3.juju-log server.go:325 indices status:
[{'health': 'green', 'status': 'open', 'index': '.opensearch-observability', 'uuid': 't4nF9pXuRuu7HK-wofO-uA', 'pri': '1', 'rep': '2', 'docs.count': '0', 'docs.deleted': '0', 'store.size': '624b', 'pri.store.size': '208b'}, {'health': 'green', 'status': 'open', 'index': '.plugins-ml-config', 'uuid': 'b8Bw9frGRumOW5p9K-gwcg', 'pri': '1', 'rep': '3', 'docs.count': '1', 'docs.deleted': '0', 'store.size': '15.7kb', 'pri.store.size': '3.9kb'}, {'health': 'green', 'status': 'open', 'index': 'series_index', 'uuid': 'fHOIVrzVTEKFJJOo9o8eGA', 'pri': '1', 'rep': '1', 'docs.count': '114500', 'docs.deleted': '0', 'store.size': '13.9mb', 'pri.store.size': '5.1mb'}, {'health': 'green', 'status': 'open', 'index': '.opendistro_security', 'uuid': 'H7nLw9ElRVaxgJP-r-13fA', 'pri': '1', 'rep': '3', 'docs.count': '10', 'docs.deleted': '2', 'store.size': '232.5kb', 'pri.store.size': '58.1kb'}]
indices shards:
[{'index': '.opensearch-observability', 'shard': '0', 'prirep': 'p', 'state': 'STARTED', 'docs': '0', 'store': '208b', 'ip': '10.112.36.243', 'node': 'opensearch-7'}, {'index': '.opensearch-observability', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '0', 'store': '208b', 'ip': '10.112.36.31', 'node': 'opensearch-8'}, {'index': '.opensearch-observability', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '0', 'store': '208b', 'ip': '10.112.36.96', 'node': 'opensearch-6'}, {'index': '.plugins-ml-config', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '1', 'store': '3.9kb', 'ip': '10.112.36.243', 'node': 'opensearch-7'}, {'index': '.plugins-ml-config', 'shard': '0', 'prirep': 'p', 'state': 'STARTED', 'docs': '1', 'store': '3.9kb', 'ip': '10.112.36.229', 'node': 'opensearch-3'}, {'index': '.plugins-ml-config', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '1', 'store': '3.9kb', 'ip': '10.112.36.31', 'node': 'opensearch-8'}, {'index': '.plugins-ml-config', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '1', 'store': '3.9kb', 'ip': '10.112.36.96', 'node': 'opensearch-6'}, {'index': 'series_index', 'shard': '0', 'prirep': 'p', 'state': 'STARTED', 'docs': '114500', 'store': '5.1mb', 'ip': '10.112.36.229', 'node': 'opensearch-3'}, {'index': 'series_index', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '118200', 'store': '8.8mb', 'ip': '10.112.36.31', 'node': 'opensearch-8'}, {'index': '.opensearch-sap-log-types-config', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': None, 'store': None, 'ip': '10.112.36.243', 'node': 'opensearch-7'}, {'index': '.opensearch-sap-log-types-config', 'shard': '0', 'prirep': 'p', 'state': 'STARTED', 'docs': None, 'store': None, 'ip': '10.112.36.229', 'node': 'opensearch-3'}, {'index': '.opensearch-sap-log-types-config', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': None, 'store': None, 'ip': '10.112.36.31', 'node': 'opensearch-8'}, {'index': '.opensearch-sap-log-types-config', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': None, 'store': None, 'ip': '10.112.36.96', 'node': 'opensearch-6'}, {'index': '.opendistro_security', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '10', 'store': '58.1kb', 'ip': '10.112.36.243', 'node': 'opensearch-7'}, {'index': '.opendistro_security', 'shard': '0', 'prirep': 'p', 'state': 'STARTED', 'docs': '10', 'store': '58.1kb', 'ip': '10.112.36.229', 'node': 'opensearch-3'}, {'index': '.opendistro_security', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '10', 'store': '58.1kb', 'ip': '10.112.36.31', 'node': 'opensearch-8'}, {'index': '.opendistro_security', 'shard': '0', 'prirep': 'r', 'state': 'STARTED', 'docs': '10', 'store': '58.1kb', 'ip': '10.112.36.96', 'node': 'opensearch-6'}]
```

Now, index `series_index` has only one replica in opensearch/8 (the leader charm unit) and opensearch/3.

Indeed, node opensearch/8 also ends up restarting at that same time:
```
2024-02-06 22:11:55 DEBUG unit.opensearch/8.juju-log server.go:325 opensearch-peers:0: Re-emitting deferred event <RunWithLock via OpenSearchOperatorCharm/on/service_run_with_lock[360]>.
2024-02-06 22:11:56 DEBUG unit.opensearch/8.juju-log server.go:325 opensearch-peers:0: Rolling Ops Manager: _start_opensearch called
2024-02-06 22:11:56 DEBUG unit.opensearch/8.juju-log server.go:325 opensearch-peers:0: _start_opensearch: opensearch is started
```

From syslog, we can see:
```
Feb  6 22:11:37 juju-215360-9 opensearch.daemon[17531]: [2024-02-06T22:11:37,435][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [opensearch-8] Detected cluster change event for destination migration
Feb  6 22:11:37 juju-215360-9 opensearch.daemon[17531]: [2024-02-06T22:11:37,451][INFO ][o.o.n.Node               ] [opensearch-8] stopping ...

...

Feb  6 22:11:52 juju-215360-9 opensearch.daemon[20842]: [2024-02-06T22:11:52,619][INFO ][o.o.s.OpenSearchSecurityPlugin] [opensearch-8] Node started
```

Looking at the logs of a 3rd unit, outside of these two:
```
Feb  6 22:11:37 juju-215360-4 opensearch.daemon[11277]: [2024-02-06T22:11:37,731][INFO ][o.o.c.s.ClusterApplierService] [opensearch-3] removed {{opensearch-8}{o0sgd9gUQUK1ZuNfpIHMMg}{ojsoi0ekRKSviDRfbjCcgg}{10.112.36.31}{10.112.36.31:9300}{coordinating_onlydiml}{shard_indexing_pressure_enabled=true}}, term: 18, version: 681, reason: ApplyCommitRequest{term=18, version=681, sourceNode={opensearch-7}{EcbGlU3rRd2FfjRU7JKxzQ}{zSij8_FgTSyo3saRuU-CuQ}{10.112.36.243}{10.112.36.243:9300}{coordinating_onlydimml}{shard_indexing_pressure_enabled=true}}
Feb  6 22:11:37 juju-215360-4 opensearch.daemon[11277]: [2024-02-06T22:11:37,737][INFO ][o.o.a.c.ADClusterEventListener] [opensearch-3] Cluster node changed, node removed: true, node added: false
Feb  6 22:11:37 juju-215360-4 opensearch.daemon[11277]: [2024-02-06T22:11:37,737][INFO ][o.o.a.c.HashRing         ] [opensearch-3] Node removed:
```

Which shows both nodes holding the index `series_index` go away at the same time, and the entire run fails before opensearch-8 is added back to the cluster.

-----------------------------------------------------------------------------------------------------------

Final Juju Status:
```
Model                         Controller           Cloud/Region         Version  SLA          Timestamp
test-horizontal-scaling-8i98  github-pr-52358-lxd  localhost/localhost  3.1.7    unsupported  22:17:39Z

App                       Version  Status   Scale  Charm                     Channel  Rev  Exposed  Message
opensearch                         blocked      4  opensearch                           0  no       1 or more 'primary' shards are not assigned, please scale your application up.
self-signed-certificates           active       1  self-signed-certificates  stable    72  no       

Unit                         Workload  Agent  Machine  Public address  Ports  Message
opensearch/3                 error     idle   4        10.112.36.229          hook failed: "storage-detaching"
opensearch/6                 active    idle   7        10.112.36.96           
opensearch/7                 active    idle   8        10.112.36.243          
opensearch/8*                active    idle   9        10.112.36.31           
self-signed-certificates/0*  active    idle   0        10.112.36.120          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.112.36.120  juju-215360-0  ubuntu@22.04      Running
4        started  10.112.36.229  juju-215360-4  ubuntu@22.04      Running
7        started  10.112.36.96   juju-215360-7  ubuntu@22.04      Running
8        started  10.112.36.243  juju-215360-8  ubuntu@22.04      Running
9        started  10.112.36.31   juju-215360-9  ubuntu@22.04      Running

Integration provider                   Requirer                     Interface         Type     Message
opensearch:opensearch-peers            opensearch:opensearch-peers  opensearch_peers  peer     
opensearch:service                     opensearch:service           rolling_op        peer     
self-signed-certificates:certificates  opensearch:certificates      tls-certificates  regular  

Storage Unit  Storage ID         Type        Pool    Mountpoint                   Size     Status    Message
opensearch/3  opensearch-data/3  filesystem  rootfs  /var/snap/opensearch/common  145 GiB  attached  
opensearch/6  opensearch-data/6  filesystem  rootfs  /var/snap/opensearch/common  145 GiB  attached  
opensearch/7  opensearch-data/7  filesystem  rootfs  /var/snap/opensearch/common  145 GiB  attached  
opensearch/8  opensearch-data/8  filesystem  rootfs  /var/snap/opensearch/common  145 GiB  attached  
```

**Comment by phvalguima** [comment]
The conclusions here are:
1) We have a scenario where two nodes may be out at the same time
2) In the CI: we have indices that hold one single replica

**Comment by Mehdi-Bendriss** [comment]
Horizontal scaling tests have been well stabilized through the implementation of the new lock mechanism as well as https://github.com/canonical/opensearch-operator/pull/279
