### ISSUE TITLE
`OpenSearchUserManager.create_user` does not distinguish between creation error and user already exists

### ISSUE THREAD

**Issue by phvalguima** [canonical/opensearch-operator#277]
The `_start_opensearch` constantly fails with errors below at `_post_start_init`.

```
unit-opensearch-0: 15:04:27 ERROR unit.opensearch/0.juju-log creating user monitor failed
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 826, in _start_opensearch
    self._post_start_init(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 925, in _post_start_init
    self._put_or_update_internal_user_leader(COSUser)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_base_charm.py", line 1115, in _put_or_update_internal_user_leader
    self.user_manager.put_internal_user(user, hashed_pwd)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_users.py", line 309, in put_internal_user
    self.create_user(COSUser, roles, hashed_pwd)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_users.py", line 179, in create_user
    raise OpenSearchUserMgmtError(f"creating user {user_name} failed")
charms.opensearch.v0.opensearch_users.OpenSearchUserMgmtError: creating user monitor failed
```

That happens because the `create_user` does not distinguish between failing to create an user because it actually failed or the user already exists. The later means the `response` returns `status_code==200` and `status=="OK"`. The method `create_role` has a similar problem but a better error handling logic:

```
        if resp.get("status") != "CREATED" and not (
            resp.get("status") == "OK" and "updated" in resp.get("message")
        ):
            logging.error(f"Couldn't create role: {resp}")
            raise OpenSearchUserMgmtError(f"creating role {role_name} failed")
```

**Comment by phvalguima** [comment]
Fixed on: https://github.com/canonical/opensearch-operator/commit/3a8597344ee54f8e3ca64ac0454093b1561d3cca, instead
