### ISSUE TITLE
OpenSearch errors with: `charms.data_platform_libs.v0.data_interfaces.PrematureDataAccessError` 

### ISSUE THREAD

**Issue by phvalguima** [canonical/opensearch-operator#492]
OpenSearch is occasionally failing with: https://pastebin.ubuntu.com/p/ZfNWHvK3yH/

Stacktrace:
```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-0/charm/./src/charm.py", line 221, in <module>
    main(OpenSearchOperatorCharm)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1924, in _on_relation_changed
    self.on.certificate_available.emit(
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_tls.py", line 270, in _on_certificate_available
    self.charm.opensearch_provider.update_certs(relation.id, ca_chain)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/opensearch/v0/opensearch_relation_provider.py", line 376, in update_certs
    self.opensearch_provides.set_tls_ca(relation_id, _ch_chain)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1692, in set_tls_ca
    self.update_relation_data(relation_id, {"tls-ca": tls_ca})
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 496, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1407, in update_relation_data
    return self._update_relation_data(relation, data)
  File "/var/lib/juju/agents/unit-opensearch-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1632, in _update_relation_data
    raise PrematureDataAccessError(
charms.data_platform_libs.v0.data_interfaces.PrematureDataAccessError: Premature access to relation data, update is forbidden before the connection is initialized.
```

**Comment by niwamo** [comment]
We recently encountered this issue also. Commenting out [lines 1709-1714](https://github.com/canonical/opensearch-operator/blob/0d5c1b2ec940f0d5c36428e5065ec6480ac84c9a/lib/charms/data_platform_libs/v0/data_interfaces.py#L1709) fixed the issue. The check was completely blocking our deployment, and removing it has not had any observable side effects in our deployment so far.
